using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace BlazorStaticNavigation.Generators;

[Generator]
public class NavigablePageGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var rootNamespaceProvider = context.AnalyzerConfigOptionsProvider.Select(
            (provider, _) =>
            {
                if (
                    !provider.GlobalOptions.TryGetValue(
                        "build_property.RootNamespace",
                        out var rootNamespace
                    ) || string.IsNullOrEmpty(rootNamespace)
                )
                {
                    throw new System.InvalidOperationException(
                        "RootNamespace build property is required but was not found."
                    );
                }
                return rootNamespace;
            }
        );

        var razorFiles = context.AdditionalTextsProvider.Where(file =>
            file.Path.EndsWith(".razor")
        );

        var razorFilesWithNamespace = razorFiles.Combine(rootNamespaceProvider);

        var pageInfos = razorFilesWithNamespace
            .Select(
                (tuple, cancellationToken) =>
                {
                    var (file, rootNamespace) = tuple;
                    var content = file.GetText(cancellationToken)?.ToString();

                    if (string.IsNullOrEmpty(content))
                        return default;

                    var route = RazorPageAnalyzer.ExtractFirstPageRoute(content!);
                    if (route == null)
                        return default;

                    var className = RazorPageAnalyzer.GetClassNameFromPath(file.Path);
                    var ns = RazorPageAnalyzer.GetNamespaceFromPath(file.Path, rootNamespace);
                    var parameters = RazorPageAnalyzer.ParseRouteParameters(route);

                    return new PageInfo(
                        ClassName: className,
                        Namespace: ns,
                        Route: route,
                        Parameters: parameters.ToImmutableArray(),
                        FilePath: file.Path
                    );
                }
            )
            .Where(info => info != default);

        context.RegisterSourceOutput(pageInfos, GenerateSource);
    }

    private void GenerateSource(SourceProductionContext context, PageInfo pageInfo)
    {
        var source = GeneratePageImplementation(pageInfo);
        var hintName = $"{pageInfo.Namespace}.{pageInfo.ClassName}.g.cs";
        context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private string GeneratePageImplementation(PageInfo pageInfo)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {pageInfo.Namespace};");
        sb.AppendLine();

        if (pageInfo.Parameters.Length == 0)
        {
            sb.AppendLine(
                $"public partial class {pageInfo.ClassName} : global::BlazorStaticNavigation.INavigablePage<{pageInfo.ClassName}>"
            );
            sb.AppendLine("{");
            sb.AppendLine($"    public static string Path => \"{pageInfo.Route}\";");
            sb.AppendLine("}");
        }
        else
        {
            var parametersRecordName = "NavigationParameters";

            sb.AppendLine(
                $"public partial class {pageInfo.ClassName} : global::BlazorStaticNavigation.INavigablePage<{pageInfo.ClassName}, {pageInfo.ClassName}.{parametersRecordName}>"
            );
            sb.AppendLine("{");
            sb.AppendLine($"    public static string Path => \"{pageInfo.Route}\";");
            sb.AppendLine();

            var recordParams = string.Join(
                ", ",
                pageInfo.Parameters.Select(p => $"{p.CSharpType} {p.Name}")
            );
            sb.AppendLine($"    public record {parametersRecordName}({recordParams});");
            sb.AppendLine();

            var interpolatedPath = RazorPageAnalyzer.GenerateInterpolatedPath(
                pageInfo.Route,
                pageInfo.Parameters.ToList()
            );
            sb.AppendLine(
                $"    public static string GetPathWithParameters({parametersRecordName} p)"
            );
            sb.AppendLine($"        => $\"{interpolatedPath}\";");

            sb.AppendLine("}");
        }

        return sb.ToString();
    }
}
